CREATE TABLE proposed_topic_watch (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      proposed_topic_id BIGINT NOT NULL,
                                      user_id BIGINT NOT NULL,
                                      CONSTRAINT fk_proposed_topic FOREIGN KEY (proposed_topic_id) REFERENCES proposed_topic(id),
                                      CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES app_user(id)
);